apiVersion: cilium.io/v1alpha1
kind: TracingPolicy
metadata:
  name: "block-process"
spec:
  kprobes:
  - call: "__x64_sys_execve"
    syscall: true 
    selectors:
    - matchPIDs:
      - operator: NotIn
        followForks: false
        isNamespacePID: true 
        values:
        - 1
      matchActions:
      - action: Sigkill
  - call: "do_execve"
    syscall: false
    selectors:
    - matchPIDs:
      - operator: NotIn
        followForks: false
        isNamespacePID: true 
        values:
        - 1
      matchActions:
      - action: Sigkill
