---
apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: check-if-image-signed
  namespace: default
spec:
  validationFailureAction: Enforce
  webhookTimeoutSeconds: 30
  background: false
  failurePolicy: Fail
  rules:
    - name: check-if-image-signed
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences:
        - "ghcr.io/nmeisenzahl/*"
        attestors:
        - count: 1
          entries:
          - keys:
              publicKeys: |-
                -----BEGIN PUBLIC KEY-----
                MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEJchD3XYjfkGiu2tmKlU0Gluj+VBq
                LqBknljBJvywMlw3aNXRyfqfEcPI078+qnm9rgjh2y24YviIRoHvkw0MjA==
                -----END PUBLIC KEY-----
